---
# tasks file for 2do_parcial

- debug:
    msg: "Tareas del 2do Parcial"

- name: Crear estructura de directorios para parcial
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

- name: Generar archivo datos_alumno.txt
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Generar archivo datos_equipo.txt
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Configurar sudoers para el grupo 2PSupervisores
  copy:
    content: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/2psupervisores
    validate: /usr/sbin/visudo -cf %s
    mode: '0440'
